name: Auto-fix Linting Issues

on:
  push:
    branches:
      - dev
      - 'feature/**'
  pull_request:
    branches: [ dev ]  # Excluded main - test.yml already verifies linting

concurrency:
  group: lint-fix-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  lint-fix:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        run: uv sync --group dev

      - name: Auto-fix linting issues
        run: |
          uv run ruff check --fix src/ tests/
          uv run ruff format src/ tests/

      - name: Commit auto-fixes if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --staged --quiet; then
            git commit -m "style: auto-fix linting issues [skip ci]"
            git push
          else
            echo "No linting fixes needed"
          fi

      - name: Verify linting passes
        run: uv run ruff check src/ tests/ --no-fix
